version: '3.8'  
  
services:  
  app:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:  
      - "8765:8765"  
    environment:  
    volumes:  
      - ./frontend:/app/frontend  
      - ./backend:/app/backend  