# Use a base image that supports both Node.js and Python installations  
FROM python:3.11 
  
# Install Node.js  
RUN apt-get update && \  
    apt-get install -y curl && \  
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \  
    apt-get install -y nodejs  
  
WORKDIR /app  
  
# Copy both frontend and backend source code  
COPY frontend ./frontend  
COPY backend ./backend  
  
# Install Node.js dependencies and build the frontend  
RUN cd frontend && npm install && npm run build  
  
# Install Python dependencies  
RUN pip install -r backend/requirements.txt  
  
  
# Expose the application port  
EXPOSE 8765  
  
# Run the backend application  
# Set the working directory to backend  
WORKDIR /app/backend  

CMD ["python", "app.py"]  